version: '3'

services:
  rabbitmq1:
    image: "rabbitmq:3-management"
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_cookie
    volumes:
      - mq1-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
 
  rabbitmq2:
    image: "rabbitmq:3-management"
    hostname: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_cookie
    volumes:
      - mq2-data:/var/lib/rabbitmq
    depends_on:
      - rabbitmq1
    links:
      - rabbitmq1
    ports:
      - "5673:5672"
      - "15673:15672"
    restart: always
 
  rabbitmq3:
    image: "rabbitmq:3-management"
    hostname: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_cookie
    volumes:
      - mq3-data:/var/lib/rabbitmq
    depends_on:
      - rabbitmq1
      - rabbitmq2
    links:
      - rabbitmq1
      - rabbitmq2
    ports:
      - "5674:5672"
      - "15674:15672"
    restart: always
 
volumes:
  mq1-data:
  mq2-data:
  mq3-data: