# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Remote write configuration (for Graphite, OpenTSDB, InfluxDB or Clickhouse).
remote_write:
    # 填写prom2click的地址
    - url: "http://prom2click:9201/write"
    #- url: "http://192.168.195.134:9201/write"
remote_read:
    - url: "http://prom2click:9201/read"
    #- url: "http://192.168.195.134:9201/read"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules/rule.yaml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs: 
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    static_configs:
      - targets: ["localhost:9090"]
      
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'node-cluster'
    static_configs:
      - targets:
        #- '192.168.195.134:9100'
        - 'clickhouse-server:9100'
  # 添加如下 clickhouse 监控
  #- job_name: "clickhouse-server"
  #  static_configs:
  #    - targets: ['192.168.195.134:9363'] # 默认端口号为 9396，要跟 clickhouse 的配置相同
